site_name: CO2 Calculator — User Docs
site_description: User documentation for the EPFL ENAC CO2 calculator.
site_url: https://epfl-enac.github.io/co2-calculator-user-doc/
repo_name: EPFL-ENAC/co2-calculator
repo_url: https://github.com/EPFL-ENAC/co2-calculator
docs_dir: docs/

theme:
  name: material
  language: en
  features:
    - navigation.top
    - navigation.tabs
    - content.code.copy
    - toc.integrate
  logo: assets/logo/epfl-logo.svg
  favicon: assets/logo/epfl-logo.svg
  palette:
    - scheme: default
      primary: white
      accent: red
      toggle: 
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - table-reader
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
          site_name: CO2 Calculator — User Docs
        - locale: fr
          name: Français
          build: true
          site_name: Calculateur de CO2 — Documentation utilisateur
          nav_translations:
            Home: Accueil
            Project Overview: Aperçu du projet
            Methodology: Méthodologie
            Modules specification: Spécification des modules
            Headcount: Effectifs  
            Buildings: Bâtiments
            Processes: Procédés
            Professional travel: Voyages professionnels
            Equipment: Équipements
            Services: Services
            Purchases: Achats
            FAQ: FAQ
            Acknowledgements: Remerciements
            Contact: Contact

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path:
        - docs
      check_paths: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


nav:
  - Home: index.md
  - Project Overview: project-overview.md
  - Methodology: methodology.md
  - Modules specification:
      - Headcount: headcount.md
      - Professional travel: professional-travel.md
      - Buildings: building.md
      - Processes: processes.md
      - Equipment: equipment.md
      - Purchases: purchases.md
      - Services: services.md
      - External clouds & IA: external-cloud.md
  - FAQ: faq.md
  - Acknowledgements: acknowledgements.md
  - Contact: contact.md
